language: c

matrix:
  include:
    - env: BUILD=DEBUG
      compiler: gcc

    - env: BUILD=RELEASE
      compiler: gcc

    - env: BUILD=DEBUG
      compiler: clang

    - env: BUILD=RELEASE
      compiler: clang

# Command to run tests
script:
  - mkdir build && cd $_
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD}
  - make
  - make test

